# Generated by Django 3.1.2 on 2021-07-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='title',
        ),
    ]
